version: '3.7'
services:
  consumer:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python3.7 consumer_main.py
    environment:
      UPLOAD_TOPIC: "test26"
      KAFKA_HOST: "kafka"
      SPARK_LOCAL: "spark://spark-master:7077"
      MONGODB_HOST : "mongodb"
      BATCH_SIZE : 200
    networks:
      - app-tier



networks:
  app-tier:
    driver: bridge
