version: '3.7'
services:
  producer:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python producer_main.py
    environment:
      UPLOAD_TOPIC: "test25"
      KAFKA_HOST: "kafka"
    networks:
      - app-tier

  consumer:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python consumer_main.py
    environment:
      UPLOAD_TOPIC: "test25"
      KAFKA_HOST: "kafka"
      SPARK_LOCAL: "spark://spark-master:7077"
    networks:
      - app-tier



networks:
  app-tier:
    driver: bridge
